name = "bg-remover"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "bg_remover_users"
database_id = "988736ce-e8f4-44d4-9f82-b38957e551c1"
